### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by u2rem** [EvgeniaN/dotnetcode.ru-code-samples#1]
http://prntscr.com/o8rk42

**Comment by u2rem** [comment]
http://prntscr.com/o8rr86

**Comment by EvgeniaN** [comment]
There is no Free.cshtml in my code.
Can you share your repository? I'll take a look.

**Comment by u2rem** [comment]
я пишу сайт один. можешь написать мне в телеграм или скайп? я начал увлекаться асп нет core, но знакомых нету которые хорошо разбираются в этом. и эта ошибка с капчей уже достала. 2 сутки сижу с ней

**Comment by u2rem** [comment]
просто опубликуй под win 64 платформу и запусти. локальный сервер. и будет та же ошибка. в визуал студии все работает, но после публикации начинаются "сюрпризы"

**Comment by EvgeniaN** [comment]
Ошибка не в капче. Она возникает при генерации вьюшки **Free.cshtml**, которой даже нет в моем коде. В этой вьюшке используется TagHelper, в коде которого возникает NullReferenceException.

**Comment by EvgeniaN** [comment]
Мне нужно увидеть код Free.cshtml, чтобы сказать что-то точнее.

**Comment by u2rem** [comment]
да в коде все нормально. в студии все работает. в том числе и в твоем поректе. но как только я публикую приложение тогда и ошибка. 
https://dropmefiles.com/3702e

**Comment by EvgeniaN** [comment]
Падает на этой строке в Free.cshtml:
`<form action="" method="post">`

Замени ее на:
`<form asp-action="Free" asp-controller="Home" method="post">`

И ContactModel не используется, убери ее из параметров в методе Free контроллера.

**Comment by u2rem** [comment]
Ок спасибо красотка. Проверю

**Comment by u2rem** [comment]
К сожалению та же ошибка. При отправке пост запроса на странице Free.
http://prntscr.com/o95xie
Но она возникает только при публикации проекта. В режиме отладки все нормально. 
http://185.251.38.153/Home/Free

**Comment by EvgeniaN** [comment]
Это уже совсем другая ошибка. Я посмотрю, в чем может быть проблема, как только появится свободное время. Постараюсь завтра ответить.

**Comment by u2rem** [comment]
Спасибо за помощь и потраченное время. Я воспользовался этим примером.
https://www.dotnetfocus.com/how-to-add-google-recaptcha-to-your-net-core-project/
Надеюсь кому то поможет.

**Comment by EvgeniaN** [comment]
Я опубликовала свой пример:
https://dotnetcode-grecaptcha-v2.azurewebsites.net/

Ошибка не воспроизвелась, но у кого-то тоже воспроизводится. Я нашла workaround:
https://groups.google.com/forum/#!topic/recaptcha/rNVX_ojf-qA

**Comment by EvgeniaN** [comment]
Я все-таки хочу разобраться. Ты можешь добавить только этот скрипт, ничего не меняя в остальном коде на основе моего примера?
`window.onload = function () {
  var $recaptcha = document.querySelector('#g-recaptcha-response');
  if ($recaptcha) {
    $recaptcha.setAttribute("required", "required");
  };`

Будет так работать?

**Comment by EvgeniaN** [comment]
Кроме этого javascript на window.onload и css я никакой разницы со своим кодом не вижу. 

Еще может быть была какая-то проблема c layout страницы в твоем случае:
https://stackoverflow.com/questions/30685443/google-recaptcha-not-posting-g-recaptcha-response

**Comment by u2rem** [comment]
Вообще ничего не менял. Просто опубликовал win64
http://prntscr.com/o9b0oa
Вот опубликованный проект
https://dropmefiles.com/Xo2Ql
Возможно проблема в моей VS

**Comment by EvgeniaN** [comment]
В данном случае падает, потому что не прописаны ключи в настройках. 

Я сейчас скачала твой архив https://dropmefiles.com/Xo2Ql, распаковала его, прописала настройки в файле appsettings.json и запустила exe. На localhost:5000 все работает отлично.

**Comment by EvgeniaN** [comment]
Чтобы совсем все вопросы отпали, показываю:
[Видео](https://drive.google.com/file/d/1bwKEjk-618wrM4J_2s8CnJhfUjg3YZV_)

**Comment by u2rem** [comment]
Значит проблема была в том, что я не правильно или не туда вписал ключи. Или вообще не вписал.  
Подтверждаю. Все работает. А в случае с моим сайтом - не знаю что это было. Скорее всего я где то накосячил. Лучше удалить эту тему чтоб не вводить людей в заблуждение.

**Comment by EvgeniaN** [comment]
Ок, разобрались. Закрываю.
